on:
  push:
  pull_request:
  schedule:
    - cron: '30 13 * * *'
jobs:
  sphinx:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run Sphinx
        run: |
          python -m pip install -r ci/requirements.txt
          python setup.py --no-c-backend install

          python -m pip install Sphinx==3.2.1
          make -C docs html
