on:
  push:
  pull_request:
  schedule:
    - cron: '30 13 * * *'
jobs:
  mypy:
    strategy:
      fail-fast: false
      matrix:
        py:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}

      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --require-hashes -r ci/requirements.txt

      - name: Run mypy
        run: |
          mypy tests/*.py zstandard/*.py
